crud/sistema/categoria/urls.py
#URLs de categoria propias 

#Se importa views para acceder a las vistas
from django.urls import path
from . import views

app_name ='home'
#Lo que esta despues de views. debe coincidir con el nombre que se dio en views.py despues de def
#despues de name= es el nomnbre que le estoy dando a esa url 

urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('nosotros', views.nosotros, name='nosotros'),

#ACCESOS A INTERFAZ DE CATEGORIA
    path('categorias',views.categoria, name='categorias'),
    path('categorias/create_categoria',views.create_categoria, name='crear'),
    path('categorias/update_categoria',views.update_categoria, name='actualizar'),
    path('delete_categoria/<str:codigo>',views.delete_categoria, name='eliminar'),
    path('categorias/update_categoria/<str:codigo>',views.update_categoria, name='actualizar'),

#ACCESOS A INTERFAZ DE CUENTA
    path('cuenta',views.cuenta, name='cuenta'),
    path('cuenta/create_cuenta',views.create_cuenta, name='crear cuenta'),
    path('cuenta/update_cuenta',views.update_cuenta, name='actualizar cuenta'),
    path('delete_cuenta/<str:username>',views.delete_cuenta, name='eliminar cuenta'),
    path('cuenta/update_cuenta/<str:username>',views.update_cuenta, name='actualizar cuenta'),

#ACCESOS A INTERFAZ DE COLECCION
    path('Colecciones/',views.Coleccionesv, name='Colecciones'),
    path('Colecciones/create_coleccion',views.create_coleccion, name='crear coleccion'),
    path('Colecciones/update_coleccion',views.update_coleccion, name='actualizar coleccion'),
    path('delete_coleccion/<str:codigo>',views.delete_coleccion, name='eliminar coleccion'),
    path('Colecciones/update_coleccion/<str:codigo>',views.update_coleccion, name='actualizar coleccion'),

    #ACCESOS A INTERFAZ DE PRODUCTO
    path('Productos',views.Productosv, name='Productos'),
    path('Productos/create_producto',views.create_producto, name='crear producto'),
    path('Productos/update_producto',views.update_producto, name='actualizar producto'),
    path('delete_producto/<str:codigo>',views.delete_producto, name='eliminar producto'),
    path('Productos/update_producto/<str:codigo>',views.update_producto, name='actualizar producto'),

    #Pagina
    path('pagina/blog.html', views.blog, name='blog'),
    path('pagina/carrito.html', views.carrito, name='carrito'),
    path('pagina/colecciones.html', views.colecciones, name='colecciones'),
    path('pagina/conocenos.html', views.conocenos, name='conocenos'),
    path('pagina/account.html', views.account, name='account'),
    path('pagina/ethereal.html', views.ethereal, name='ethereal'),
    path('pagina/houseofcards.html', views.houseofcards, name='houseofcards'),
    path('pagina/index.html', views.index, name='index'),
    path('pagina/login.html', views.login, name='login'),
    path('pagina/magicglam.html', views.magicglam, name='magicglam'),
    path('pagina/pago.html', views.pago, name='pago'),
    path('pagina/prueba.html', views.prueba, name='prueba'),
    path('pagina/registro.html', views.Signup.as_view(), name='registro'),


]

crud/sistema/sistema/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('categoria.urls')),
    
]

crud/sistema/categoria/models.py
from django.db import models

#MODELO DE CATEGORIAS
class categorias(models.Model):
    codigo = models.CharField(primary_key=True, max_length=5)
    nombre = models.CharField(max_length=30)

    class Meta:
        managed = False
        db_table = 'categorias'

##MODELO DE CUENTA
class Cuenta(models.Model):
    username = models.CharField(primary_key=True, max_length=15)
    email = models.CharField(unique=True, max_length=50, blank=True, null=True)
    contraseña = models.CharField(max_length=15)

    class Meta:
        managed = False
        db_table = 'cuenta'
        
#MODELO DE COLECCIONES
class Colecciones(models.Model):
    codigo = models.CharField(primary_key=True, max_length=5)
    nombre = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=200)
    categoria = models.ForeignKey(categorias, models.DO_NOTHING, db_column='categoria', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'colecciones'

#MODELO DE PRODUCTOS 
class Productos(models.Model):
    codigo = models.CharField(primary_key=True, max_length=5)
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=250)
    precio = models.FloatField()
    stock = models.IntegerField()
    colecciones = models.ForeignKey(Colecciones, models.DO_NOTHING, db_column='colecciones')

    class Meta:
        managed = False 
        db_table = 'productos'

crud/sistema/categoria/forms.py
from django import forms
from .models import *
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import categorias, Cuenta, Colecciones, Productos

class categoriaForm(forms.ModelForm):
    class Meta:
        model = categorias
        fields = '__all__'

class cuentaForm(forms.ModelForm):
    class Meta:
        model = Cuenta
        fields = '__all__'

class coleccionesForm(forms.ModelForm):
    class Meta:
        model = Colecciones
        fields = '__all__'

class ProductosForm(forms.ModelForm):
    class Meta:
        model = Productos
        fields = '__all__' 



class SignupForm(UserCreationForm):
    username = forms.CharField(max_length=16, widget=forms.TextInput(attrs={"type":"text", "class":"bx bx-user"}))
    first_name = forms.CharField(max_length=16, widget=forms.TextInput(attrs={"type":"text", "class":"bx bx-user"}))
    last_name = forms.CharField(max_length=16, widget=forms.TextInput(attrs={"type":"text", "class":"bx bx-user"}))
    email = forms.CharField(max_length=32, widget=forms.TextInput(attrs={"type":"text", "class":"bx bx-user"}))

crud/sistema/categoria/views.py
#CREACION DE VISTAS
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import generic
from django.urls import reverse_lazy
from .models import *
from .forms import *

#DECLARACION DE FUNCION
#Se esta realizando solicitud y se responde con un texto en html

def inicio (request):
    return render(request,'paginas/inicio.html')

def nosotros(request):
    return render(request,'paginas/nosotros.html')
#ACCESO A SECCIONES DE PAGINAS 


#ACCESO A CATEGORIAS
def categoria(request):
    categoria = categorias.objects.all()
    print(categorias)
    return render (request,'categorias/index.html',{'categorias':categoria})

def create_categoria(request):
    formulario = categoriaForm(request.POST or None, request.FILES or None)
    if formulario.is_valid():
        formulario.save()
        return redirect('home:categorias')
    return render(request,'categorias/create_categoria.html', {'formulario': formulario})

def update_categoria(request, codigo):
    categoria = categorias.objects.get(codigo=codigo)
    formulario = categoriaForm(request.POST or None, request.FILES or None, instance=categoria)
    if formulario.is_valid() and request.POST:
      formulario.save()
      return redirect('home:categorias')
    return render(request,'categorias/update_categoria.html', {'formulario':formulario})

def delete_categoria(request, codigo):
    categoria = categorias.objects.get(codigo=codigo)
    categoria.delete()
    return redirect('home:categorias')


#ACCESO A CUENTAS
def cuenta(request):
    cuentas = Cuenta.objects.all()
    return render (request,'cuentas/index.html',{'Cuenta':cuentas})

def create_cuenta(request):
    formulario = cuentaForm(request.POST or None, request.FILES or None)
    if formulario.is_valid():
        formulario.save()
        return redirect('home:cuenta')
    return render(request,'cuentas/create_cuenta.html', {'formulario': formulario})

def update_cuenta(request, username):
    cuenta = Cuenta.objects.get(username=username)
    formulario = cuentaForm(request.POST or None, request.FILES or None, instance=cuenta)
    if formulario.is_valid() and request.POST:
      formulario.save()
      return redirect('home:cuenta')
    return render(request,'cuentas/update_cuenta.html', {'formulario':formulario})

def delete_cuenta(request, username):
    cuenta = Cuenta.objects.get(username=username)
    cuenta.delete()
    return redirect('home:cuenta')

#ACCESO A COLECCION
def Coleccionesv(request):
    Coleccion = Colecciones.objects.all()
    return render(request,'Coleccionesc/index.html',{'colecciones':Coleccion})

def create_coleccion(request):
    formulario = coleccionesForm(request.POST or None, request.FILES or None)
    if formulario.is_valid():
        formulario.save()
        return redirect('home:Colecciones')
    return render(request,'Coleccionesc/create_coleccion.html', {'formulario': formulario})

def update_coleccion(request, codigo):
    Coleccionesv = Colecciones.objects.get(codigo=codigo)
    formulario = coleccionesForm(request.POST or None, request.FILES or None, instance=Coleccionesv)
    if formulario.is_valid() and request.POST:
      formulario.save()
      return redirect('home:Colecciones')
    return render(request,'Coleccionesc/update_coleccion.html', {'formulario':formulario})

def delete_coleccion(request, codigo):
    Coleccionesv = Colecciones.objects.get(codigo=codigo)
    Coleccionesv.delete()
    return redirect('home:Colecciones')

#ACCESO A PRODUCTO
def Productosv(request):
    Producto = Productos.objects.all()
    return render(request,'productosc/index.html',{'Productos':Producto})

def create_producto(request):
    formulario = ProductosForm(request.POST or None, request.FILES or None)
    if formulario.is_valid():
        formulario.save()
        return redirect('home:Productos')
    return render(request,'productosc/create_producto.html', {'formulario': formulario})

def update_producto(request, codigo):
    Productosv = Productos.objects.get(codigo=codigo)
    formulario = ProductosForm(request.POST or None, request.FILES or None, instance=Productosv)
    if formulario.is_valid() and request.POST:
      formulario.save()
      return redirect('home:Productos')
    return render(request,'productosc/update_producto.html', {'formulario':formulario})

def delete_producto(request, codigo):
    Productosv = Productos.objects.get(codigo=codigo)
    Productosv.delete()
    return redirect('home:Productos') 

#PAGINAS

def blog(request):
    return render(request,'pagina/blog.html')

def carrito(request):
    return render(request,'pagina/carrito.html')

def colecciones(request):
    return render(request,'pagina/colecciones.html')

def conocenos(request):
    return render(request,'pagina/conocenos.html')

def account(request):
    return render(request,'pagina/account.html')

def ethereal(request):
    return render(request,'pagina/ethereal.html')

def houseofcards(request):
    return render(request,'pagina/houseofcards.html')

def index(request):
    return render(request,'pagina/index.html')

def login(request):
    return render(request,'pagina/login.html')

def magicglam(request):
    return render(request,'pagina/magicglam.html')

def pago(request):
    return render(request,'pagina/pago.html')

def prueba(request):
    return render(request,'pagina/prueba.html')

# def registro(request):
#     return render(request,'pagina/registro.html')


class Signup(generic.CreateView):
    template_name = "pagina/registro.html"
    model = User
    form_class = SignupForm
    success_url = reverse_lazy("home:inicio")

crud/sistema/categoria/templates/categorias/create_categoria.html
<!--CREATE-CREAR 
#Para ingresar los datos de la nueva categoria -->

{% extends "base.html" %}

{% block titulo %} Agregar nueva categoria {% endblock %}

{% block contenido %} 

<div class="card">
    <div class="card-header">
        Crear una categoria
    </div>
    <div class="card-body">
        <h4 class="card-title">Datos de la categoria</h4>

        {% include 'categorias/form.html' %}

    </div>
    <div class="card-footer text-muted">
    </div>
</div>

{% endblock %}

crud/sistema/categoria/templates/categorias/form.html
<form enctype="multipart/form-data" method="post" >

  {% csrf_token  %}
  {% for campo in formulario %}

    <div class="mb-3">
      <label for="" class="form-label">{{campo.label}} </label>
      <input 
      type="{{campo.field.wodget.input_type}}"
      class="form-control" 
      name="{{campo.name}}" 
      id="" 
      aria-describedby="helpId" 
      placeholder="{{campo.label}}"
      value="{{campo.value | default:''}}"
      >
    </div>
    <div class="col-12 help-text"> {{campo.errors}} </div>
    {%endfor%}
    <input name="" id="" class="btn btn-success" type="submit" value="Enviar informacion">
    <a name="" id="" class="btn btn-primary" href="{% url 'home:categorias' %}" role="button">Cancelar</a>
</form>

crud/sistema/categoria/templates/categorias/index.html
{% extends "base.html" %}

{% block titulo %} Lista de categorias {% endblock %}

{% block contenido %} 

<div class="card">
    <div class="card-header">
        <a name="" id="" class="btn btn-success" href="{% url 'home:crear' %}" role="button">Agregar nueva categoria</a>
    </div>
    <div class="card-body">
        <h4 class="card-title">Categorias</h4>

        <table class="table table-primary">
                <thead>
                    <tr>
                        <th> codigo </th>
                        <th> nombre </th>
                        <th> acciones </th>
                    </tr>
                </thead>
                <tbody>
                    {% for categoria in categorias %}
                    <tr>
                        <td>{{ categoria.codigo }}</td>
                        <td>{{ categoria.nombre }}</td>
                        <td> <a name="" id="" class="btn btn-info" href="{% url 'home:actualizar' categoria.codigo %}" role="button">Actualizar</a> 
                            |
                            <a name="" id="" class="btn btn-danger" href="{% url 'home:eliminar' categoria.codigo %}" role="button">Borrar</a> </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

        </div>       
    </div>
    <div class="card-footer text-muted">
    </div>
</div>

{% endblock %}

crud/sistema/categoria/templates/categorias/update_categoria.html
<!--UPDATE-ACTUALIZAR 
#Para ingresar los datos de la nueva categoria -->

{% extends "base.html" %}

{% block titulo %} Actualizar categoria {% endblock %}

{% block contenido %} 


<div class="card">
    <div class="card-header">
        Actualizar una categoria
    </div>
    <div class="card-body">
        <h4 class="card-title">Datos de la categoria</h4>

        {% include 'categorias/form.html' %}

    </div>
    <div class="card-footer text-muted">
    </div>
</div>

{% endblock %}